name: Run all tests with AddressSanitizer enabled

on:
  schedule:
    - cron: "40 4 * * *"

jobs:
  specs:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - name: fix kernel mmap rnd bits for ASan
        run: sudo sysctl vm.mmap_rnd_bits=28
      - name: get commit count
        run: echo "NEW_COMMIT_COUNT=$(git log --oneline --since '25 hours ago' | wc -l)" >> $GITHUB_ENV
      - name: run tests
        if: ${{ env.NEW_COMMIT_COUNT > 0 }}
        env:
          SPEC_TIMEOUT: 480
        run: rake docker_test_asan
