name: Format

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: install dependencies
        run: |
          sudo apt-get install -y -q ruby clang-format build-essential
          sudo gem install bundler
          bundle config set --local path vendor/bundle
          bundle install
      - name: format
        run: bundle exec rake format
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: Tim Morgan
          author_email: tim@timmorgan.org
          message: "Format code (automated)"
