name: Lint

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOCKER_FLAGS: ""
  CI: 1

jobs:
  clang-tidy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - name: checkout submodules
        run: git submodule update --init --recursive
      - name: run clang-tidy
        run: rake docker_tidy
  gc-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - name: checkout submodules
        run: git submodule update --init --recursive
      - name: run gc-lint
        run: rake docker_gc_lint
