name: Run all specs from ruby/spec

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  BUNDLE_WITH: run_all_specs

jobs:
  specs:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - run: rake docker_test_all_ruby_spec_nightly
        env:
          STATS_API_SECRET: ${{ secrets.STATS_API_SECRET }}
          NAT_BUILD_MODE: debug
