name: Run all tests with the bootstrapped self-hosted compiler

on:
  schedule:
    - cron: "40 2 * * *"

jobs:
  specs:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - name: get commit count
        run: echo "NEW_COMMIT_COUNT=$(git log --oneline --since '25 hours ago' | wc -l)" >> $GITHUB_ENV
      - name: run tests
        if: ${{ env.NEW_COMMIT_COUNT > 0 }}
        run: rake docker_test_self_hosted_full
